### ISSUE TITLE
Add-on is not staying active after the page was refreshed 

### ISSUE THREAD

**Issue by scombette** [antitoine/stay-productive#1]
Hi, 

I tried your add-on with Firefox 50.1.0 on Win7 64 bits. 

I used it on Facebook, and I noticed that when I refresh the page on my browser, the add-on doesn't stay active, however, the add-on icon stays on the activated position. 

Thank you. 

Sébastien.

**Comment by antitoine** [comment]
Thanks for the feedback!
The bug is fixed and a new release (v0.3) will arrive soon.
