### ISSUE TITLE
Facebook right panel keeps displaying feed

### ISSUE THREAD

**Issue by scombette** [antitoine/stay-productive#2]
Hi, 

I tried your add-on with Firefox 50.1.0 on Win7 64 bits. 

I used it on Facebook, and I noticed that the right panel keeps displaying news even if the add-on is activated. For a next version, could you please try to hide hit ? 

Thank you. 

Sébastien.

**Comment by antitoine** [comment]
Thanks again for you submission.
This is a good idea! This feature was added [here](https://github.com/antitoine/stay-productive/commit/8cfcd7c6070fba20e58418d70b83883af54145b8) and will be deployed soon.
