### ISSUE TITLE
Change default settings to ON

### ISSUE THREAD

**Issue by pciazynski** [antitoine/stay-productive#6]
It would be nice if default setting is ON. Or maybe better it would be if this addition remember ON/OFF setting for each website even after closing tab or closing browser. I think is better to stay productive if you don't want to manually kill news feed each time, what do you think? ;)

**Comment by antitoine** [comment]
Good point! Even better, choose in the setting of the add-on what default behavior the user wants. I will try to do it when I will have more time (not before 2 weeks), or if you want to contribute to this, I will appreciate it a lot.
With the new version of firefox (53.0), I notice that the state of the add-on in a tab is saved and restored. So I will not make any progress on this for now. What browser do you use?
Thanks for your feedback!

**Comment by pciazynski** [comment]
For now I use Firefox 52.0.1. So yeah, maybe for now I will just upgrade my browser :)

**Comment by antitoine** [comment]
The new version 0.5 (e40c889) is submitted for reviewing (only at mozilla for now).
Your add-on will be updated automatically when this task is completed (max 48 hours).
If all is okay after a few days, I will propagate the new version in Chrome and Opera.

In this version you can choose the default behavior (activate it by default or not). Like I said, normally in the Firefox 53, the tab state is restored, so I make any progress on this point.

Let me know if you find any bug and thanks again for the feedback.

**Comment by pciazynski** [comment]
Nice, I checked it - it works nice in Firefox 52 and in Firefox 53 too :) Thank you very much :)

**Comment by antitoine** [comment]
Great! ;)

**Comment by Ardnived** [comment]
Did you ever propagate this change to Opera? (I'm using the latest Opera 49.0)

The extension isn't on by default, nor does it remember. It seems almost useless to me with this behaviour unfortunately. :/

**Comment by antitoine** [comment]
@Ardnived Infortunatly, I haven't propagate the v0.5 on Chrome and Opera because the behavior isn't the same. If you need it, I will test it soon and deploy the new version ;)

**Comment by antitoine** [comment]
@Ardnived I just released version 0.5 on the Chrome Store and the Opera Store. You should have the update in a few hours.

**Comment by Ardnived** [comment]
Great, thanks so much Antoine, I appreciate it.
